[package]
name = "data-room-adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
data-room-schema = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
csv = { workspace = true }

[dev-dependencies]
zip = { workspace = true }
