[package]
name = "mm-quote"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mm-quote"
path = "src/main.rs"

[dependencies]
mm-bot  = { path = "../../services/mm-bot" }
pricing = { workspace = true }

clap   = { workspace = true }
anyhow = { workspace = true }
