//! hedge-signer.
//!
//! Protocol-side co-signer for a trading vault's EXTERNAL ACCOUNT — the
//! jointly-controlled address that holds venue capital (docs/mm-bot-v2
//! 03 §3b). Its key is jointly held (curator + this service), so every
//! account transaction needs both signatures. This service contributes its
//! signature ONLY when the transaction passes the policy engine
//! ([`policy`]), which approves exactly one Sui-transaction shape: the
//! sweep back to the vault. Every decision is appended to an audit log
//! ([`audit`]).
//!
//! The Bluefin/FROST substrate is the sibling signing path ([`frost`] +
//! [`policy::bluefin`]): each vault's Bluefin parent account key is a
//! 2-of-2 threshold-ed25519 key (one share here, one with the curator),
//! generated by a two-round DKG and used in a two-round FROST signing
//! ceremony over detached venue payloads. The payload policy runs before
//! any signature share leaves the service.
//!
//! Endpoints (all on one public port, proxied by nginx):
//! - `GET /health`
//! - `GET /pubkey` — the service key's public key, address, and scheme (so
//!   operators can construct the 2-of-2 multisig address).
//! - `GET /policy` — summary of the loaded policy (no secrets).
//! - `POST /sign` — classify a `TransactionData` and, on approval, return
//!   the service signature over it.
//! - `GET /frost/pubkey/:vault_id` — the vault's group ed25519 key + parent
//!   Sui address.
//! - `GET /frost/registration/:vault_id` — ed25519 attestation, signed by
//!   the service key, that the vault's FROST parent address is co-held here
//!   (input to `vault::set_external_account_attested`).
//! - `POST /frost/keygen/round1|round2` — per-vault DKG (curator ↔ service),
//!   open to any live vault that has no external account registered yet
//!   ([`chain`]); the per-vault config gates SIGNING only.
//! - `POST /frost/sign/round1|round2` — payload-policy-gated two-round
//!   FROST signing.
//! - `/bluefin/{auth|data|trade}/*` — allowlisted Bluefin REST relay for the
//!   curator dashboard ([`bluefin_proxy`]; Bluefin CORS-blocks third-party
//!   origins). Holds no keys, forwards only client-signed payloads.

pub mod audit;
pub mod bluefin_proxy;
pub mod chain;
pub mod config;
pub mod frost;
pub mod frost_handlers;
pub mod handlers;
pub mod policy;
pub mod router;
pub mod state;

pub use config::Config;
pub use state::AppState;

use std::path::PathBuf;

use clap::{Parser, Subcommand};

#[derive(Parser, Debug)]
#[command(
    name = "hedge-signer",
    about = "Policy-gated co-signer for trading-vault external accounts (2-of-2 multisig member)."
)]
pub struct Cli {
    #[arg(
        short,
        long,
        global = true,
        default_value = "services/hedge-signer/config/config.toml"
    )]
    pub config: PathBuf,

    /// Secrets TOML holding the service's `[sui]` signing key. No env-var
    /// fallback.
    #[arg(
        short = 's',
        long,
        global = true,
        default_value = "services/hedge-signer/config/secrets.toml"
    )]
    pub secrets: PathBuf,

    /// No subcommand runs the service.
    #[command(subcommand)]
    pub command: Option<Command>,
}

#[derive(Subcommand, Debug)]
pub enum Command {
    /// Delete a vault's stored FROST share so the vault can run keygen
    /// again. Deliberately conservative and un-forceable: refuses unless
    /// the parent address is provably orphaned — not registered as the
    /// vault's on-chain external account, and holding no coin balances.
    PruneShare {
        /// TradingVault shared-object id.
        vault_id: String,
    },
}

cli_spec::define_program! {
    id          = "hedge-signer",
    cargo_pkg   = "hedge-signer",
    working_dir = ".",
    description = "Hedge signer. Holds the protocol member key of each trading vault's 2-of-2 \
                   external account and countersigns account transactions that pass the \
                   three-tier policy engine (auto / strict / emergency).",
    cli         = crate::Cli,
}
