[package]
name = "exchange_adapter"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
exchange = { local = "../exchange" }
trading_vault = { local = "../trading-vault" }
options_core = { local = "../core" }
