[package]
name = "exchange_adapter"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
exchange = { local = "../exchange" }
whitelist = { local = "../whitelist" }
vault_v2 = { local = "../trading-vault-v2" }
options_core = { local = "../core" }
