//! Canonical wire format for multichain trading-vault messages
//! (docs/multichain-vault-plan.md §2.1).
//!
//! This crate is the SOURCE OF TRUTH for the byte layout. The Move codec
//! (`vault_v2::wire`) and the Solidity codec (`evm-contracts/src/lib/
//! Wire.sol`) implement the same layout and are pinned to the golden
//! fixtures under `fixtures/` — regenerated by `cargo test -p
//! vault-messages` (see `tests` below); any layout change must update all
//! three codecs and the fixtures in one commit.
//!
//! ## Layout rules
//!
//! - All integers are FIXED-WIDTH BIG-ENDIAN (no varints), so every
//!   message is byte-deterministic and cheap to parse in Solidity and
//!   Move alike.
//! - Addresses/ids travel as 32 bytes: Sui addresses as-is, EVM addresses
//!   left-padded with zeros.
//! - Amounts travel as u128. Sui-side consumers must reject values above
//!   u64::MAX; EVM-side producers must revert on amounts above u128::MAX.
//! - Booleans are one byte, 0 or 1; any other value is a decode error.
//!
//! ## Envelope (90-byte header ‖ payload)
//!
//! | field        | width | notes                                   |
//! |--------------|-------|-----------------------------------------|
//! | version      | 1     | must be `WIRE_VERSION`                  |
//! | msg_type     | 1     | `MsgType` discriminant                  |
//! | src_chain_id | 8     | protocol chain id (config-assigned)     |
//! | dst_chain_id | 8     |                                         |
//! | src_app      | 32    | sending vault (hub object id / spoke)   |
//! | dst_app      | 32    | receiving vault                         |
//! | seq          | 8     | per (src,dst,app-pair), strictly rising |

use thiserror::Error;

pub const WIRE_VERSION: u8 = 1;
pub const ENVELOPE_LEN: usize = 90;

/// Hard cap on `StateSync.integration_raw`, mirrored in both on-chain
/// codecs so a spoke cannot grease an unboundedly large message through.
pub const MAX_INTEGRATION_RAW_LEN: usize = 4096;
pub const MAX_STATE_SYNC_ASSETS: usize = 16;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum MsgType {
    DepositNotice = 1,
    WithdrawRequest = 2,
    PayoutReceipt = 3,
    StateSync = 4,
    DepositAck = 5,
    WithdrawAck = 6,
    ConfigSync = 7,
}

impl MsgType {
    pub fn from_u8(v: u8) -> Result<Self, WireError> {
        Ok(match v {
            1 => Self::DepositNotice,
            2 => Self::WithdrawRequest,
            3 => Self::PayoutReceipt,
            4 => Self::StateSync,
            5 => Self::DepositAck,
            6 => Self::WithdrawAck,
            7 => Self::ConfigSync,
            other => return Err(WireError::UnknownMsgType(other)),
        })
    }
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum WireError {
    #[error("unsupported wire version {0}")]
    UnsupportedVersion(u8),
    #[error("unknown message type {0}")]
    UnknownMsgType(u8),
    #[error("message truncated: wanted {wanted} bytes, had {had}")]
    Truncated { wanted: usize, had: usize },
    #[error("trailing bytes after payload: {0}")]
    TrailingBytes(usize),
    #[error("invalid boolean byte {0}")]
    InvalidBool(u8),
    #[error("integration_raw length {0} exceeds cap")]
    IntegrationRawTooLong(usize),
    #[error("state sync asset count {0} exceeds cap")]
    TooManyAssets(usize),
    #[error("payload type does not match envelope msg_type")]
    TypeMismatch,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Envelope {
    pub src_chain_id: u64,
    pub dst_chain_id: u64,
    pub src_app: [u8; 32],
    pub dst_app: [u8; 32],
    pub seq: u64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Payload {
    /// Spoke → hub: raw deposit fact. No valuation fields by design.
    /// `ts_ms` is the spoke block timestamp of the deposit — the hub
    /// refuses to ACK past the reclaim deadline measured from it.
    DepositNotice {
        spoke_id: u64,
        deposit_seq: u64,
        depositor: [u8; 32],
        asset: u8,
        amount: u128,
        tranche: u8,
        ts_ms: u64,
    },
    /// Spoke → hub: share-denominated withdrawal ask.
    WithdrawRequest {
        spoke_id: u64,
        request_seq: u64,
        user: [u8; 32],
        tranche: u8,
        shares: u128,
        all: bool,
    },
    /// Spoke → hub: a queued payout physically settled.
    PayoutReceipt {
        spoke_id: u64,
        request_seq: u64,
        amount: u128,
    },
    /// Spoke → hub: raw balances snapshot (never a valuation).
    StateSync {
        spoke_id: u64,
        assets: Vec<StateSyncAsset>,
        fee_pot_balance: u128,
        integration_raw: Vec<u8>,
        ts_ms: u64,
    },
    /// Hub → spoke: mint record instruction (shares hub-computed).
    DepositAck {
        deposit_seq: u64,
        accepted: bool,
        shares: u128,
    },
    /// Hub → spoke: pay instruction.
    WithdrawAck {
        request_seq: u64,
        user: [u8; 32],
        pay_amount: u128,
    },
    /// Hub → spoke: gate/identity propagation.
    ConfigSync {
        paused: bool,
        risk_off: bool,
        curator: [u8; 32],
        endpoint: u8,
        integrations_root: [u8; 32],
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StateSyncAsset {
    pub asset: u8,
    pub free: u128,
    pub reserved: u128,
}

impl Payload {
    pub fn msg_type(&self) -> MsgType {
        match self {
            Payload::DepositNotice { .. } => MsgType::DepositNotice,
            Payload::WithdrawRequest { .. } => MsgType::WithdrawRequest,
            Payload::PayoutReceipt { .. } => MsgType::PayoutReceipt,
            Payload::StateSync { .. } => MsgType::StateSync,
            Payload::DepositAck { .. } => MsgType::DepositAck,
            Payload::WithdrawAck { .. } => MsgType::WithdrawAck,
            Payload::ConfigSync { .. } => MsgType::ConfigSync,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Message {
    pub envelope: Envelope,
    pub payload: Payload,
}

// ─────────────────────────────── encode ───────────────────────────────

struct Writer(Vec<u8>);

impl Writer {
    fn u8(&mut self, v: u8) {
        self.0.push(v);
    }
    fn boolean(&mut self, v: bool) {
        self.0.push(v as u8);
    }
    fn u64(&mut self, v: u64) {
        self.0.extend_from_slice(&v.to_be_bytes());
    }
    fn u128(&mut self, v: u128) {
        self.0.extend_from_slice(&v.to_be_bytes());
    }
    fn bytes32(&mut self, v: &[u8; 32]) {
        self.0.extend_from_slice(v);
    }
}

pub fn encode(msg: &Message) -> Vec<u8> {
    let mut w = Writer(Vec::with_capacity(ENVELOPE_LEN + 128));
    w.u8(WIRE_VERSION);
    w.u8(msg.payload.msg_type() as u8);
    w.u64(msg.envelope.src_chain_id);
    w.u64(msg.envelope.dst_chain_id);
    w.bytes32(&msg.envelope.src_app);
    w.bytes32(&msg.envelope.dst_app);
    w.u64(msg.envelope.seq);
    match &msg.payload {
        Payload::DepositNotice { spoke_id, deposit_seq, depositor, asset, amount, tranche, ts_ms } => {
            w.u64(*spoke_id);
            w.u64(*deposit_seq);
            w.bytes32(depositor);
            w.u8(*asset);
            w.u128(*amount);
            w.u8(*tranche);
            w.u64(*ts_ms);
        }
        Payload::WithdrawRequest { spoke_id, request_seq, user, tranche, shares, all } => {
            w.u64(*spoke_id);
            w.u64(*request_seq);
            w.bytes32(user);
            w.u8(*tranche);
            w.u128(*shares);
            w.boolean(*all);
        }
        Payload::PayoutReceipt { spoke_id, request_seq, amount } => {
            w.u64(*spoke_id);
            w.u64(*request_seq);
            w.u128(*amount);
        }
        Payload::StateSync { spoke_id, assets, fee_pot_balance, integration_raw, ts_ms } => {
            assert!(assets.len() <= MAX_STATE_SYNC_ASSETS, "asset cap");
            assert!(integration_raw.len() <= MAX_INTEGRATION_RAW_LEN, "raw cap");
            w.u64(*spoke_id);
            w.u8(assets.len() as u8);
            for a in assets {
                w.u8(a.asset);
                w.u128(a.free);
                w.u128(a.reserved);
            }
            w.u128(*fee_pot_balance);
            w.0.extend_from_slice(&(integration_raw.len() as u16).to_be_bytes());
            w.0.extend_from_slice(integration_raw);
            w.u64(*ts_ms);
        }
        Payload::DepositAck { deposit_seq, accepted, shares } => {
            w.u64(*deposit_seq);
            w.boolean(*accepted);
            w.u128(*shares);
        }
        Payload::WithdrawAck { request_seq, user, pay_amount } => {
            w.u64(*request_seq);
            w.bytes32(user);
            w.u128(*pay_amount);
        }
        Payload::ConfigSync { paused, risk_off, curator, endpoint, integrations_root } => {
            w.boolean(*paused);
            w.boolean(*risk_off);
            w.bytes32(curator);
            w.u8(*endpoint);
            w.bytes32(integrations_root);
        }
    }
    w.0
}

// ─────────────────────────────── decode ───────────────────────────────

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn take(&mut self, n: usize) -> Result<&'a [u8], WireError> {
        if self.pos + n > self.buf.len() {
            return Err(WireError::Truncated { wanted: self.pos + n, had: self.buf.len() });
        }
        let s = &self.buf[self.pos..self.pos + n];
        self.pos += n;
        Ok(s)
    }
    fn u8(&mut self) -> Result<u8, WireError> {
        Ok(self.take(1)?[0])
    }
    fn boolean(&mut self) -> Result<bool, WireError> {
        match self.u8()? {
            0 => Ok(false),
            1 => Ok(true),
            b => Err(WireError::InvalidBool(b)),
        }
    }
    fn u16(&mut self) -> Result<u16, WireError> {
        Ok(u16::from_be_bytes(self.take(2)?.try_into().unwrap()))
    }
    fn u64(&mut self) -> Result<u64, WireError> {
        Ok(u64::from_be_bytes(self.take(8)?.try_into().unwrap()))
    }
    fn u128(&mut self) -> Result<u128, WireError> {
        Ok(u128::from_be_bytes(self.take(16)?.try_into().unwrap()))
    }
    fn bytes32(&mut self) -> Result<[u8; 32], WireError> {
        Ok(self.take(32)?.try_into().unwrap())
    }
}

pub fn decode(bytes: &[u8]) -> Result<Message, WireError> {
    let mut r = Reader { buf: bytes, pos: 0 };
    let version = r.u8()?;
    if version != WIRE_VERSION {
        return Err(WireError::UnsupportedVersion(version));
    }
    let msg_type = MsgType::from_u8(r.u8()?)?;
    let envelope = Envelope {
        src_chain_id: r.u64()?,
        dst_chain_id: r.u64()?,
        src_app: r.bytes32()?,
        dst_app: r.bytes32()?,
        seq: r.u64()?,
    };
    let payload = match msg_type {
        MsgType::DepositNotice => Payload::DepositNotice {
            spoke_id: r.u64()?,
            deposit_seq: r.u64()?,
            depositor: r.bytes32()?,
            asset: r.u8()?,
            amount: r.u128()?,
            tranche: r.u8()?,
            ts_ms: r.u64()?,
        },
        MsgType::WithdrawRequest => Payload::WithdrawRequest {
            spoke_id: r.u64()?,
            request_seq: r.u64()?,
            user: r.bytes32()?,
            tranche: r.u8()?,
            shares: r.u128()?,
            all: r.boolean()?,
        },
        MsgType::PayoutReceipt => Payload::PayoutReceipt {
            spoke_id: r.u64()?,
            request_seq: r.u64()?,
            amount: r.u128()?,
        },
        MsgType::StateSync => {
            let spoke_id = r.u64()?;
            let n = r.u8()? as usize;
            if n > MAX_STATE_SYNC_ASSETS {
                return Err(WireError::TooManyAssets(n));
            }
            let mut assets = Vec::with_capacity(n);
            for _ in 0..n {
                assets.push(StateSyncAsset { asset: r.u8()?, free: r.u128()?, reserved: r.u128()? });
            }
            let fee_pot_balance = r.u128()?;
            let raw_len = r.u16()? as usize;
            if raw_len > MAX_INTEGRATION_RAW_LEN {
                return Err(WireError::IntegrationRawTooLong(raw_len));
            }
            let integration_raw = r.take(raw_len)?.to_vec();
            let ts_ms = r.u64()?;
            Payload::StateSync { spoke_id, assets, fee_pot_balance, integration_raw, ts_ms }
        }
        MsgType::DepositAck => Payload::DepositAck {
            deposit_seq: r.u64()?,
            accepted: r.boolean()?,
            shares: r.u128()?,
        },
        MsgType::WithdrawAck => Payload::WithdrawAck {
            request_seq: r.u64()?,
            user: r.bytes32()?,
            pay_amount: r.u128()?,
        },
        MsgType::ConfigSync => Payload::ConfigSync {
            paused: r.boolean()?,
            risk_off: r.boolean()?,
            curator: r.bytes32()?,
            endpoint: r.u8()?,
            integrations_root: r.bytes32()?,
        },
    };
    if r.pos != bytes.len() {
        return Err(WireError::TrailingBytes(bytes.len() - r.pos));
    }
    Ok(Message { envelope, payload })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn addr(tag: u8) -> [u8; 32] {
        let mut a = [0u8; 32];
        a[31] = tag;
        a[0] = 0xa0 | tag;
        a
    }

    fn envelope(seq: u64) -> Envelope {
        Envelope {
            src_chain_id: 0x0000_0000_0000_0101,
            dst_chain_id: 0x0000_0000_0000_0001,
            src_app: addr(2),
            dst_app: addr(1),
            seq,
        }
    }

    /// The golden fixture set. One entry per message type, chosen with
    /// non-trivial values in every field (high bits set on amounts so an
    /// endianness slip cannot pass).
    pub(crate) fn golden_messages() -> Vec<(&'static str, Message)> {
        vec![
            (
                "deposit_notice",
                Message {
                    envelope: envelope(7),
                    payload: Payload::DepositNotice {
                        spoke_id: 3,
                        deposit_seq: 41,
                        depositor: addr(0xd),
                        asset: 1,
                        amount: 250_000_000_000_000_001u128,
                        tranche: 2,
                        ts_ms: 1_756_400_000_555,
                    },
                },
            ),
            (
                "withdraw_request",
                Message {
                    envelope: envelope(8),
                    payload: Payload::WithdrawRequest {
                        spoke_id: 3,
                        request_seq: 9,
                        user: addr(0xd),
                        tranche: 1,
                        shares: 0x0102_0304_0506_0708_090a_0b0c_0d0e_0f10u128,
                        all: false,
                    },
                },
            ),
            (
                "payout_receipt",
                Message {
                    envelope: envelope(9),
                    payload: Payload::PayoutReceipt {
                        spoke_id: 3,
                        request_seq: 9,
                        amount: 1_000_000_007u128,
                    },
                },
            ),
            (
                "state_sync",
                Message {
                    envelope: envelope(10),
                    payload: Payload::StateSync {
                        spoke_id: 3,
                        assets: vec![
                            StateSyncAsset { asset: 1, free: 5_000_000_000, reserved: 1_234 },
                            StateSyncAsset { asset: 2, free: 0, reserved: u64::MAX as u128 + 1 },
                        ],
                        fee_pot_balance: 777_000_000_000_000_000u128,
                        integration_raw: vec![0xde, 0xad, 0xbe, 0xef],
                        ts_ms: 1_756_500_000_123,
                    },
                },
            ),
            (
                "deposit_ack",
                Message {
                    envelope: envelope(11),
                    payload: Payload::DepositAck {
                        deposit_seq: 41,
                        accepted: true,
                        shares: 123_456_789_012_345_678u128,
                    },
                },
            ),
            (
                "withdraw_ack",
                Message {
                    envelope: envelope(12),
                    payload: Payload::WithdrawAck {
                        request_seq: 9,
                        user: addr(0xd),
                        pay_amount: 999_999_999u128,
                    },
                },
            ),
            (
                "config_sync",
                Message {
                    envelope: envelope(13),
                    payload: Payload::ConfigSync {
                        paused: false,
                        risk_off: true,
                        curator: addr(0xc),
                        endpoint: 1,
                        integrations_root: addr(0xe),
                    },
                },
            ),
        ]
    }

    #[test]
    fn round_trip_golden() {
        for (name, msg) in golden_messages() {
            let bytes = encode(&msg);
            let back = decode(&bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
            assert_eq!(back, msg, "{name}");
        }
    }

    /// Golden fixtures are committed under fixtures/<name>.hex; this test
    /// fails if the byte layout drifts from them. Regenerate deliberately
    /// with BLESS_FIXTURES=1 (and update the Move + Solidity codecs).
    #[test]
    fn golden_fixtures_stable() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures");
        for (name, msg) in golden_messages() {
            let bytes = encode(&msg);
            let hex_now: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
            let path = dir.join(format!("{name}.hex"));
            if std::env::var("BLESS_FIXTURES").is_ok() {
                std::fs::create_dir_all(&dir).unwrap();
                std::fs::write(&path, &hex_now).unwrap();
                continue;
            }
            let committed = std::fs::read_to_string(&path)
                .unwrap_or_else(|_| panic!("{name}: missing fixture, run with BLESS_FIXTURES=1"));
            assert_eq!(committed.trim(), hex_now, "{name}: wire layout drifted from fixture");
        }
    }

    #[test]
    fn rejects_bad_version_type_bool_and_trailing() {
        let (_, msg) = &golden_messages()[0];
        let good = encode(msg);

        let mut bad = good.clone();
        bad[0] = 9;
        assert_eq!(decode(&bad), Err(WireError::UnsupportedVersion(9)));

        let mut bad = good.clone();
        bad[1] = 99;
        assert_eq!(decode(&bad), Err(WireError::UnknownMsgType(99)));

        let mut trailing = good.clone();
        trailing.push(0);
        assert_eq!(decode(&trailing), Err(WireError::TrailingBytes(1)));

        assert!(matches!(decode(&good[..good.len() - 1]), Err(WireError::Truncated { .. })));

        // accepted byte of deposit_ack must be 0/1
        let (_, ack) = &golden_messages()[4];
        let mut bytes = encode(ack);
        bytes[ENVELOPE_LEN + 8] = 2;
        assert_eq!(decode(&bytes), Err(WireError::InvalidBool(2)));
    }
}
