[package]
name = "deepbook_adapter"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
deepbook = { local = "../vendor/deepbook" }
token = { local = "../vendor/token" }
trading_vault = { local = "../trading-vault" }
options_core = { local = "../core" }
whitelist = { local = "../whitelist" }

