module options_protocol::errors;

public fun quote_expired(): u64 { 1 }
public fun quote_nonce_used(): u64 { 2 }
public fun quote_signature_invalid(): u64 { 3 }
public fun quote_protocol_mismatch(): u64 { 4 }
public fun quote_bucket_mismatch(): u64 { 5 }
public fun quote_account_mismatch(): u64 { 6 }
public fun quote_recipient_mismatch(): u64 { 7 }
public fun bucket_expired(): u64 { 8 }
public fun bucket_not_expired(): u64 { 9 }
public fun bucket_not_drained(): u64 { 10 }
public fun insufficient_account_balance(): u64 { 11 }
public fun amount_mismatch(): u64 { 12 }
public fun settlement_amount_mismatch(): u64 { 13 }
public fun cursor_overflow(): u64 { 14 }
public fun not_owner(): u64 { 15 }
public fun position_bucket_mismatch(): u64 { 16 }
public fun call_option_bucket_mismatch(): u64 { 17 }
public fun fee_too_high(): u64 { 18 }
public fun nonce_still_valid(): u64 { 19 }
public fun insufficient_treasury_balance(): u64 { 20 }
public fun zero_amount(): u64 { 21 }
public fun count_must_be_positive(): u64 { 22 }
public fun invalid_signing_scheme(): u64 { 23 }
public fun invalid_pubkey_length(): u64 { 24 }
public fun strike_scale_too_large(): u64 { 25 }
public fun bucket_invalidated(): u64 { 26 }
public fun bucket_not_invalidated(): u64 { 27 }
public fun treasury_cap_not_fresh(): u64 { 28 }
public fun rfq_closed(): u64 { 29 }
public fun rfq_not_closed(): u64 { 30 }
public fun rfq_bid_too_low(): u64 { 31 }
public fun rfq_bucket_mismatch(): u64 { 32 }
public fun rfq_too_close_to_expiry(): u64 { 33 }
public fun rfq_duration_too_short(): u64 { 34 }
public fun vault_wrong_phase(): u64 { 35 }
public fun vault_bucket_not_selected(): u64 { 36 }
public fun vault_bucket_already_selected(): u64 { 37 }
public fun vault_selling_closed(): u64 { 38 }
public fun vault_positions_pending(): u64 { 39 }
public fun vault_rfqs_open(): u64 { 40 }
public fun vault_round_not_finalized(): u64 { 41 }
public fun vault_receipt_round_mismatch(): u64 { 42 }
public fun vault_strike_out_of_band(): u64 { 43 }
public fun vault_expiry_out_of_band(): u64 { 44 }
public fun vault_slice_too_large(): u64 { 45 }
public fun vault_too_many_rfqs(): u64 { 46 }
public fun vault_deposits_paused(): u64 { 47 }
public fun vault_wrong_origin(): u64 { 48 }
public fun oracle_feed_mismatch(): u64 { 49 }
public fun oracle_price_stale(): u64 { 50 }
public fun oracle_confidence(): u64 { 51 }
public fun oracle_price_invalid(): u64 { 52 }
public fun vault_proceeds_unswapped(): u64 { 53 }
public fun vault_config_invalid(): u64 { 54 }
public fun vault_wrong_pool(): u64 { 55 }
public fun session_mismatch(): u64 { 56 }
public fun position_not_found(): u64 { 57 }
