/// Cross-language conformance fixtures (spec §5.2) — release-blocking.
///
/// These vectors are generated by the Rust side
/// (`orderbook/crates/signing`, `cargo run --example gen_fixtures`) and
/// asserted in BOTH test suites. Any BCS drift (field order, integer width,
/// string encoding of type names), any hashing drift (domain tag, intent
/// wrapping), or any signature-scheme drift breaks every signature in the
/// system; this file is the guard.
#[test_only]
#[allow(implicit_const_copy)]
module exchange::conformance_tests;

use std::string;
use exchange::order;

const REGISTRY_ADDR: address = @0x5c01aabbccddeeff00112233445566778899aabbccddeeff0011223344556677;
const MANAGER_ADDR: address = @0x71aa000000000000000000000000000000000000000000000000000000000001;

const ED25519_MAKER: address = @0xa0ccc8bcc83f6c628340134f8546a21e0618fd1aaa02432bba454c4a2c2233da;
const SECP256K1_MAKER: address = @0xff54162ff5cf6c25b2f6985ef274f1709ccf58175188a572ecfea4b1423c8ca0;
const DELEGATED_SIGNER: address = @0x7799ea80594c35644321148485238c7a7a1c6549809e1795e6747c6d4da2504c;

const ED25519_DIGEST: vector<u8> = x"0cb63badd00581ca252a84e4d711083c3e464c4f1c238b989331a16115b4be2d";
const ED25519_PK: vector<u8> = x"ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c";
const ED25519_SIG: vector<u8> = x"eb43b61e8e5743b6dc98fe49672d234d900ab6fd879b86aee894f3804435051da37593b73cad255d6a56b03b092f5cc68e40620e54229eb21fad1ae0bf4b720f";

const SECP256K1_DIGEST: vector<u8> = x"73a7e73d3311674b2bb29755619a9c34e0a40adf7bc09e1cf1e37c8354953547";
const SECP256K1_PK: vector<u8> = x"0256b328b30c8bf5839e24058747879408bdb36241dc9c2e7c619faa12b2920967";
const SECP256K1_SIG: vector<u8> = x"ef2bebbc46715d1a03f2b3d3a55e071727e488d8435da7a45d66087689c46e224278b1da65756413348d9909863b2a585423ac0a7a5387be88158cb37c7d1617";

const DELEGATED_PK: vector<u8> = x"8139770ea87d175f56a35466c34c7ecccb8d8a91b4ee37a25df60f5b8fc9b394";
const DELEGATED_SIG: vector<u8> = x"52bd77ce48f1e213be65b09c33539f307a4ff1acf46907b668adfcf6309d69231819c8435b3ea0fc37524a8629cc6f1a33bff27f3b4e9743d6685445ec90ad0f";

fun fixture_order(maker: address): order::Order {
    order::new_for_testing(
        string::utf8(
            b"0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI",
        ),
        string::utf8(
            b"0x00000000000000000000000000000000000000000000000000000000000000aa::usdc::USDC",
        ),
        50_000_000_000,
        125_000_000,
        10,
        maker,
        MANAGER_ADDR.to_id(),
        @0x0,
        @0x0,
        1_754_330_000_000,
        1_754_329_100_123,
    )
}

fun prefixed(scheme: u8, sig: vector<u8>): vector<u8> {
    let mut v = vector[scheme];
    v.append(sig);
    v
}

#[test]
fun ed25519_vector() {
    let ord = fixture_order(ED25519_MAKER);
    let d = order::digest(&ord, REGISTRY_ADDR.to_id());
    assert!(d == ED25519_DIGEST, 0);

    let roundtrip = order::from_bytes(order::to_bytes(&ord));
    assert!(order::digest(&roundtrip, REGISTRY_ADDR.to_id()) == ED25519_DIGEST, 1);

    let (ok, signer) = order::verify_signature(&d, &prefixed(0x00, ED25519_SIG), &ED25519_PK);
    assert!(ok, 2);
    assert!(signer == ED25519_MAKER, 3);
}

#[test]
fun secp256k1_vector() {
    let ord = fixture_order(SECP256K1_MAKER);
    let d = order::digest(&ord, REGISTRY_ADDR.to_id());
    assert!(d == SECP256K1_DIGEST, 0);

    let (ok, signer) =
        order::verify_signature(&d, &prefixed(0x01, SECP256K1_SIG), &SECP256K1_PK);
    assert!(ok, 1);
    assert!(signer == SECP256K1_MAKER, 2);
}

#[test]
fun delegated_signer_vector() {
    // Same order/digest as the ed25519 vector (maker is the owner key), but
    // signed by the hot key: verification succeeds and derives the HOT key's
    // address — settlement then checks it against the manager's approved set.
    let ord = fixture_order(ED25519_MAKER);
    let d = order::digest(&ord, REGISTRY_ADDR.to_id());
    assert!(d == ED25519_DIGEST, 0);

    let (ok, signer) = order::verify_signature(&d, &prefixed(0x00, DELEGATED_SIG), &DELEGATED_PK);
    assert!(ok, 1);
    assert!(signer == DELEGATED_SIGNER, 2);
    assert!(signer != ED25519_MAKER, 3);
}

#[test]
fun tampered_digest_fails() {
    let mut d = ED25519_DIGEST;
    let b = d[0];
    *&mut d[0] = b ^ 1;
    let (ok, _) = order::verify_signature(&d, &prefixed(0x00, ED25519_SIG), &ED25519_PK);
    assert!(!ok, 0);
}

#[test]
fun registry_binding_changes_digest() {
    // Same order bytes on another market/deployment hash differently (§7.2).
    let ord = fixture_order(ED25519_MAKER);
    let other = @0x5c01aabbccddeeff00112233445566778899aabbccddeeff0011223344556678;
    assert!(order::digest(&ord, other.to_id()) != ED25519_DIGEST, 0);
}
