[package]
name = "deepbook-pool-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "deepbook-pool-test"
path = "src/main.rs"

[dependencies]
sui-tx         = { workspace = true }
runtime-config = { workspace = true }

sui-types          = { workspace = true }
move-core-types    = { workspace = true }
shared-crypto      = { workspace = true }

clap               = { workspace = true }
anyhow             = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
