[package]
name = "deployment-manager"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "deploy"
path = "src/main.rs"

[dependencies]
protocol-types = { workspace = true }
runtime-config = { workspace = true }
cli-spec       = { workspace = true }
sui-tx         = { workspace = true }
hex            = "0.4"
sha2           = { workspace = true }
deployments    = { workspace = true }
move-publish   = { workspace = true }

sui-types = { workspace = true }
sui-keys = { workspace = true }
sui-move-build = { workspace = true }
sui-package-alt = { workspace = true }
sui-json = { workspace = true }
sui-transaction-builder = { workspace = true }
shared-crypto = { workspace = true }
move-core-types = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

clap = { workspace = true }
chrono = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
