[package]
name = "price-charting"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
runtime-config = { workspace = true }
observability = { workspace = true, features = ["axum"] }
cli-spec = { workspace = true }
api-service-client = { workspace = true }
token-info-client = { workspace = true }

sui-sdk = { workspace = true }
sui-types = { workspace = true }
sui-tx = { workspace = true }

clap = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
axum = { version = "0.7", default-features = false, features = ["http1", "json", "query", "tokio", "ws"] }
tower-http = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
metrics = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }

diesel = { workspace = true }
diesel_migrations = { workspace = true }
bigdecimal = { workspace = true }
