/// Byte-marker alphabet, low half (0x00..0x7F). See `option_coin` for the
/// encoding these spell. Split across two modules because Sui caps datatype
/// definitions per module below 256 (verified empirically at publish).
module options_core::enc0;

public struct B00 has drop {}
public struct B01 has drop {}
public struct B02 has drop {}
public struct B03 has drop {}
public struct B04 has drop {}
public struct B05 has drop {}
public struct B06 has drop {}
public struct B07 has drop {}
public struct B08 has drop {}
public struct B09 has drop {}
public struct B0A has drop {}
public struct B0B has drop {}
public struct B0C has drop {}
public struct B0D has drop {}
public struct B0E has drop {}
public struct B0F has drop {}
public struct B10 has drop {}
public struct B11 has drop {}
public struct B12 has drop {}
public struct B13 has drop {}
public struct B14 has drop {}
public struct B15 has drop {}
public struct B16 has drop {}
public struct B17 has drop {}
public struct B18 has drop {}
public struct B19 has drop {}
public struct B1A has drop {}
public struct B1B has drop {}
public struct B1C has drop {}
public struct B1D has drop {}
public struct B1E has drop {}
public struct B1F has drop {}
public struct B20 has drop {}
public struct B21 has drop {}
public struct B22 has drop {}
public struct B23 has drop {}
public struct B24 has drop {}
public struct B25 has drop {}
public struct B26 has drop {}
public struct B27 has drop {}
public struct B28 has drop {}
public struct B29 has drop {}
public struct B2A has drop {}
public struct B2B has drop {}
public struct B2C has drop {}
public struct B2D has drop {}
public struct B2E has drop {}
public struct B2F has drop {}
public struct B30 has drop {}
public struct B31 has drop {}
public struct B32 has drop {}
public struct B33 has drop {}
public struct B34 has drop {}
public struct B35 has drop {}
public struct B36 has drop {}
public struct B37 has drop {}
public struct B38 has drop {}
public struct B39 has drop {}
public struct B3A has drop {}
public struct B3B has drop {}
public struct B3C has drop {}
public struct B3D has drop {}
public struct B3E has drop {}
public struct B3F has drop {}
public struct B40 has drop {}
public struct B41 has drop {}
public struct B42 has drop {}
public struct B43 has drop {}
public struct B44 has drop {}
public struct B45 has drop {}
public struct B46 has drop {}
public struct B47 has drop {}
public struct B48 has drop {}
public struct B49 has drop {}
public struct B4A has drop {}
public struct B4B has drop {}
public struct B4C has drop {}
public struct B4D has drop {}
public struct B4E has drop {}
public struct B4F has drop {}
public struct B50 has drop {}
public struct B51 has drop {}
public struct B52 has drop {}
public struct B53 has drop {}
public struct B54 has drop {}
public struct B55 has drop {}
public struct B56 has drop {}
public struct B57 has drop {}
public struct B58 has drop {}
public struct B59 has drop {}
public struct B5A has drop {}
public struct B5B has drop {}
public struct B5C has drop {}
public struct B5D has drop {}
public struct B5E has drop {}
public struct B5F has drop {}
public struct B60 has drop {}
public struct B61 has drop {}
public struct B62 has drop {}
public struct B63 has drop {}
public struct B64 has drop {}
public struct B65 has drop {}
public struct B66 has drop {}
public struct B67 has drop {}
public struct B68 has drop {}
public struct B69 has drop {}
public struct B6A has drop {}
public struct B6B has drop {}
public struct B6C has drop {}
public struct B6D has drop {}
public struct B6E has drop {}
public struct B6F has drop {}
public struct B70 has drop {}
public struct B71 has drop {}
public struct B72 has drop {}
public struct B73 has drop {}
public struct B74 has drop {}
public struct B75 has drop {}
public struct B76 has drop {}
public struct B77 has drop {}
public struct B78 has drop {}
public struct B79 has drop {}
public struct B7A has drop {}
public struct B7B has drop {}
public struct B7C has drop {}
public struct B7D has drop {}
public struct B7E has drop {}
public struct B7F has drop {}
