/// Byte-marker alphabet, high half (0x80..0xFF) — see `enc0`.
module options_core::enc1;

public struct B80 has drop {}
public struct B81 has drop {}
public struct B82 has drop {}
public struct B83 has drop {}
public struct B84 has drop {}
public struct B85 has drop {}
public struct B86 has drop {}
public struct B87 has drop {}
public struct B88 has drop {}
public struct B89 has drop {}
public struct B8A has drop {}
public struct B8B has drop {}
public struct B8C has drop {}
public struct B8D has drop {}
public struct B8E has drop {}
public struct B8F has drop {}
public struct B90 has drop {}
public struct B91 has drop {}
public struct B92 has drop {}
public struct B93 has drop {}
public struct B94 has drop {}
public struct B95 has drop {}
public struct B96 has drop {}
public struct B97 has drop {}
public struct B98 has drop {}
public struct B99 has drop {}
public struct B9A has drop {}
public struct B9B has drop {}
public struct B9C has drop {}
public struct B9D has drop {}
public struct B9E has drop {}
public struct B9F has drop {}
public struct BA0 has drop {}
public struct BA1 has drop {}
public struct BA2 has drop {}
public struct BA3 has drop {}
public struct BA4 has drop {}
public struct BA5 has drop {}
public struct BA6 has drop {}
public struct BA7 has drop {}
public struct BA8 has drop {}
public struct BA9 has drop {}
public struct BAA has drop {}
public struct BAB has drop {}
public struct BAC has drop {}
public struct BAD has drop {}
public struct BAE has drop {}
public struct BAF has drop {}
public struct BB0 has drop {}
public struct BB1 has drop {}
public struct BB2 has drop {}
public struct BB3 has drop {}
public struct BB4 has drop {}
public struct BB5 has drop {}
public struct BB6 has drop {}
public struct BB7 has drop {}
public struct BB8 has drop {}
public struct BB9 has drop {}
public struct BBA has drop {}
public struct BBB has drop {}
public struct BBC has drop {}
public struct BBD has drop {}
public struct BBE has drop {}
public struct BBF has drop {}
public struct BC0 has drop {}
public struct BC1 has drop {}
public struct BC2 has drop {}
public struct BC3 has drop {}
public struct BC4 has drop {}
public struct BC5 has drop {}
public struct BC6 has drop {}
public struct BC7 has drop {}
public struct BC8 has drop {}
public struct BC9 has drop {}
public struct BCA has drop {}
public struct BCB has drop {}
public struct BCC has drop {}
public struct BCD has drop {}
public struct BCE has drop {}
public struct BCF has drop {}
public struct BD0 has drop {}
public struct BD1 has drop {}
public struct BD2 has drop {}
public struct BD3 has drop {}
public struct BD4 has drop {}
public struct BD5 has drop {}
public struct BD6 has drop {}
public struct BD7 has drop {}
public struct BD8 has drop {}
public struct BD9 has drop {}
public struct BDA has drop {}
public struct BDB has drop {}
public struct BDC has drop {}
public struct BDD has drop {}
public struct BDE has drop {}
public struct BDF has drop {}
public struct BE0 has drop {}
public struct BE1 has drop {}
public struct BE2 has drop {}
public struct BE3 has drop {}
public struct BE4 has drop {}
public struct BE5 has drop {}
public struct BE6 has drop {}
public struct BE7 has drop {}
public struct BE8 has drop {}
public struct BE9 has drop {}
public struct BEA has drop {}
public struct BEB has drop {}
public struct BEC has drop {}
public struct BED has drop {}
public struct BEE has drop {}
public struct BEF has drop {}
public struct BF0 has drop {}
public struct BF1 has drop {}
public struct BF2 has drop {}
public struct BF3 has drop {}
public struct BF4 has drop {}
public struct BF5 has drop {}
public struct BF6 has drop {}
public struct BF7 has drop {}
public struct BF8 has drop {}
public struct BF9 has drop {}
public struct BFA has drop {}
public struct BFB has drop {}
public struct BFC has drop {}
public struct BFD has drop {}
public struct BFE has drop {}
public struct BFF has drop {}
