//! Registry of every program the TUI knows about.
//!
//! Each entry comes from the binary crate's own `program_spec()` function,
//! which is generated by `shared::define_program!` on its `Cli` struct. The
//! clap derive is the single source of truth for flag metadata.

use shared::program_spec::ProgramSpec;

/// Every binary in the workspace, in display order.
pub fn all() -> Vec<ProgramSpec> {
    vec![
        indexer::program_spec(),
        quoting_service::program_spec(),
        mm_bot::program_spec(),
        option_scheduler::program_spec(),
        exchange::program_spec(),
        writer::program_spec(),
        deployment_manager::program_spec(),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_loads_every_binary_with_some_flags() {
        let specs = all();
        let ids: Vec<&str> = specs.iter().map(|s| s.id).collect();
        assert_eq!(
            ids,
            vec![
                "indexer",
                "quoting-service",
                "mm-bot",
                "option-scheduler",
                "exchange",
                "writer",
                "deploy",
            ]
        );
        // Every spec should produce a non-empty flag list. The lone exception
        // would be a binary with literally zero CLI args; none of ours
        // qualify.
        for s in &specs {
            assert!(
                !s.arg_specs().is_empty(),
                "{} should expose at least one flag",
                s.id
            );
        }
        // exchange is the only one with subcommands today.
        let exchange = specs.iter().find(|s| s.id == "exchange").unwrap();
        let subs = exchange.subcommand_specs();
        assert!(
            subs.iter().any(|s| s.name == "create-buckets"),
            "exchange should expose `create-buckets`"
        );
    }
}
