// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {Wire} from "../src/lib/Wire.sol";

/// @dev External wrappers so vm.expectRevert can observe Wire's reverts.
contract WireHarness {
    function decodeEnvelope(bytes memory b) external pure returns (uint8, Wire.Envelope memory) {
        return Wire.decodeEnvelope(b);
    }

    function decodeDepositNotice(bytes memory b) external pure returns (Wire.DepositNotice memory) {
        return Wire.decodeDepositNotice(b);
    }

    function decodeWithdrawRequest(bytes memory b)
        external
        pure
        returns (Wire.WithdrawRequest memory)
    {
        return Wire.decodeWithdrawRequest(b);
    }

    function decodePayoutReceipt(bytes memory b) external pure returns (Wire.PayoutReceipt memory) {
        return Wire.decodePayoutReceipt(b);
    }

    function decodeStateSync(bytes memory b) external pure returns (Wire.StateSync memory) {
        return Wire.decodeStateSync(b);
    }

    function decodeDepositAck(bytes memory b) external pure returns (Wire.DepositAck memory) {
        return Wire.decodeDepositAck(b);
    }

    function decodeWithdrawAck(bytes memory b) external pure returns (Wire.WithdrawAck memory) {
        return Wire.decodeWithdrawAck(b);
    }

    function decodeConfigSync(bytes memory b) external pure returns (Wire.ConfigSync memory) {
        return Wire.decodeConfigSync(b);
    }

    function encodeStateSync(Wire.Envelope memory e, Wire.StateSync memory p)
        external
        pure
        returns (bytes memory)
    {
        return Wire.encodeStateSync(e, p);
    }
}

/// @notice Pins Wire.sol to the golden fixtures generated by the Rust
///         source-of-truth crate (`rust-backend/crates/vault-messages`,
///         fixtures/*.hex, field values in its `golden_messages()` test
///         fn). Every fixture must decode to those exact values and
///         re-encode to the exact same bytes.
contract WireGoldenTest is Test {
    WireHarness h;

    // fixtures/*.hex, hardcoded verbatim.
    bytes constant DEPOSIT_NOTICE =
        hex"010100000000000001010000000000000001a200000000000000000000000000000000000000000000000000000000000002a100000000000000000000000000000000000000000000000000000000000001000000000000000700000000000000030000000000000029ad0000000000000000000000000000000000000000000000000000000000000d01000000000000000003782dace9d900010200000198f1991e2b";
    bytes constant WITHDRAW_REQUEST =
        hex"010200000000000001010000000000000001a200000000000000000000000000000000000000000000000000000000000002a100000000000000000000000000000000000000000000000000000000000001000000000000000800000000000000030000000000000009ad0000000000000000000000000000000000000000000000000000000000000d010102030405060708090a0b0c0d0e0f1000";
    bytes constant PAYOUT_RECEIPT =
        hex"010300000000000001010000000000000001a200000000000000000000000000000000000000000000000000000000000002a1000000000000000000000000000000000000000000000000000000000000010000000000000009000000000000000300000000000000090000000000000000000000003b9aca07";
    bytes constant STATE_SYNC =
        hex"010400000000000001010000000000000001a200000000000000000000000000000000000000000000000000000000000002a100000000000000000000000000000000000000000000000000000000000001000000000000000a000000000000000302010000000000000000000000012a05f200000000000000000000000000000004d202000000000000000000000000000000000000000000000001000000000000000000000000000000000ac875621e7a80000004deadbeef00000198f78efd7b";
    bytes constant DEPOSIT_ACK =
        hex"010500000000000001010000000000000001a200000000000000000000000000000000000000000000000000000000000002a100000000000000000000000000000000000000000000000000000000000001000000000000000b000000000000002901000000000000000001b69b4ba630f34e";
    bytes constant WITHDRAW_ACK =
        hex"010600000000000001010000000000000001a200000000000000000000000000000000000000000000000000000000000002a100000000000000000000000000000000000000000000000000000000000001000000000000000c0000000000000009ad0000000000000000000000000000000000000000000000000000000000000d0000000000000000000000003b9ac9ff";
    bytes constant CONFIG_SYNC =
        hex"010700000000000001010000000000000001a200000000000000000000000000000000000000000000000000000000000002a100000000000000000000000000000000000000000000000000000000000001000000000000000d0001ac0000000000000000000000000000000000000000000000000000000000000c01ae0000000000000000000000000000000000000000000000000000000000000e";

    // Rust `addr(tag)`: byte0 = 0xa0|tag, byte31 = tag.
    bytes32 constant ADDR_1 = hex"a100000000000000000000000000000000000000000000000000000000000001";
    bytes32 constant ADDR_2 = hex"a200000000000000000000000000000000000000000000000000000000000002";
    bytes32 constant ADDR_C = hex"ac0000000000000000000000000000000000000000000000000000000000000c";
    bytes32 constant ADDR_D = hex"ad0000000000000000000000000000000000000000000000000000000000000d";
    bytes32 constant ADDR_E = hex"ae0000000000000000000000000000000000000000000000000000000000000e";

    function setUp() public {
        h = new WireHarness();
    }

    function _split(bytes memory m)
        internal
        pure
        returns (bytes memory env, bytes memory payload)
    {
        env = new bytes(Wire.ENVELOPE_LEN);
        payload = new bytes(m.length - Wire.ENVELOPE_LEN);
        for (uint256 i = 0; i < Wire.ENVELOPE_LEN; i++) {
            env[i] = m[i];
        }
        for (uint256 i = 0; i < payload.length; i++) {
            payload[i] = m[Wire.ENVELOPE_LEN + i];
        }
    }

    function _checkEnvelope(Wire.Envelope memory e, uint64 seq) internal pure {
        assertEq(e.srcChainId, 0x101);
        assertEq(e.dstChainId, 1);
        assertEq(e.srcApp, ADDR_2);
        assertEq(e.dstApp, ADDR_1);
        assertEq(e.seq, seq);
    }

    // ─────────────────── golden: decode + re-encode ────────────────────

    function test_golden_depositNotice() public view {
        (bytes memory env, bytes memory payload) = _split(DEPOSIT_NOTICE);
        (uint8 t, Wire.Envelope memory e) = Wire.decodeEnvelope(env);
        assertEq(t, Wire.MSG_DEPOSIT_NOTICE);
        _checkEnvelope(e, 7);
        Wire.DepositNotice memory p = Wire.decodeDepositNotice(payload);
        assertEq(p.spokeId, 3);
        assertEq(p.depositSeq, 41);
        assertEq(p.depositor, ADDR_D);
        assertEq(p.asset, 1);
        assertEq(p.amount, 250_000_000_000_000_001);
        assertEq(p.tranche, 2);
        assertEq(p.tsMs, 1_756_400_000_555);
        assertEq(Wire.encodeDepositNotice(e, p), DEPOSIT_NOTICE);
    }

    function test_golden_withdrawRequest() public view {
        (bytes memory env, bytes memory payload) = _split(WITHDRAW_REQUEST);
        (uint8 t, Wire.Envelope memory e) = Wire.decodeEnvelope(env);
        assertEq(t, Wire.MSG_WITHDRAW_REQUEST);
        _checkEnvelope(e, 8);
        Wire.WithdrawRequest memory p = Wire.decodeWithdrawRequest(payload);
        assertEq(p.spokeId, 3);
        assertEq(p.requestSeq, 9);
        assertEq(p.user, ADDR_D);
        assertEq(p.tranche, 1);
        assertEq(p.shares, 0x0102030405060708090a0b0c0d0e0f10);
        assertEq(p.all, false);
        assertEq(Wire.encodeWithdrawRequest(e, p), WITHDRAW_REQUEST);
    }

    function test_golden_payoutReceipt() public view {
        (bytes memory env, bytes memory payload) = _split(PAYOUT_RECEIPT);
        (uint8 t, Wire.Envelope memory e) = Wire.decodeEnvelope(env);
        assertEq(t, Wire.MSG_PAYOUT_RECEIPT);
        _checkEnvelope(e, 9);
        Wire.PayoutReceipt memory p = Wire.decodePayoutReceipt(payload);
        assertEq(p.spokeId, 3);
        assertEq(p.requestSeq, 9);
        assertEq(p.amount, 1_000_000_007);
        assertEq(Wire.encodePayoutReceipt(e, p), PAYOUT_RECEIPT);
    }

    function test_golden_stateSync() public view {
        (bytes memory env, bytes memory payload) = _split(STATE_SYNC);
        (uint8 t, Wire.Envelope memory e) = Wire.decodeEnvelope(env);
        assertEq(t, Wire.MSG_STATE_SYNC);
        _checkEnvelope(e, 10);
        Wire.StateSync memory p = Wire.decodeStateSync(payload);
        assertEq(p.spokeId, 3);
        assertEq(p.assets.length, 2);
        assertEq(p.assets[0].asset, 1);
        assertEq(p.assets[0].free, 5_000_000_000);
        assertEq(p.assets[0].reserved, 1_234);
        assertEq(p.assets[1].asset, 2);
        assertEq(p.assets[1].free, 0);
        assertEq(p.assets[1].reserved, uint128(type(uint64).max) + 1);
        assertEq(p.feePotBalance, 777_000_000_000_000_000);
        assertEq(p.integrationRaw, hex"deadbeef");
        assertEq(p.tsMs, 1_756_500_000_123);
        assertEq(Wire.encodeStateSync(e, p), STATE_SYNC);
    }

    function test_golden_depositAck() public view {
        (bytes memory env, bytes memory payload) = _split(DEPOSIT_ACK);
        (uint8 t, Wire.Envelope memory e) = Wire.decodeEnvelope(env);
        assertEq(t, Wire.MSG_DEPOSIT_ACK);
        _checkEnvelope(e, 11);
        Wire.DepositAck memory p = Wire.decodeDepositAck(payload);
        assertEq(p.depositSeq, 41);
        assertEq(p.accepted, true);
        assertEq(p.shares, 123_456_789_012_345_678);
        assertEq(Wire.encodeDepositAck(e, p), DEPOSIT_ACK);
    }

    function test_golden_withdrawAck() public view {
        (bytes memory env, bytes memory payload) = _split(WITHDRAW_ACK);
        (uint8 t, Wire.Envelope memory e) = Wire.decodeEnvelope(env);
        assertEq(t, Wire.MSG_WITHDRAW_ACK);
        _checkEnvelope(e, 12);
        Wire.WithdrawAck memory p = Wire.decodeWithdrawAck(payload);
        assertEq(p.requestSeq, 9);
        assertEq(p.user, ADDR_D);
        assertEq(p.payAmount, 999_999_999);
        assertEq(Wire.encodeWithdrawAck(e, p), WITHDRAW_ACK);
    }

    function test_golden_configSync() public view {
        (bytes memory env, bytes memory payload) = _split(CONFIG_SYNC);
        (uint8 t, Wire.Envelope memory e) = Wire.decodeEnvelope(env);
        assertEq(t, Wire.MSG_CONFIG_SYNC);
        _checkEnvelope(e, 13);
        Wire.ConfigSync memory p = Wire.decodeConfigSync(payload);
        assertEq(p.paused, false);
        assertEq(p.riskOff, true);
        assertEq(p.curator, ADDR_C);
        assertEq(p.endpoint, 1);
        assertEq(p.integrationsRoot, ADDR_E);
        assertEq(Wire.encodeConfigSync(e, p), CONFIG_SYNC);
    }

    // ───────────────────────── reject cases ────────────────────────────

    function test_rejects_badVersion() public {
        (bytes memory env,) = _split(DEPOSIT_NOTICE);
        env[0] = 0x09;
        vm.expectRevert(abi.encodeWithSelector(Wire.UnsupportedVersion.selector, 9));
        h.decodeEnvelope(env);
    }

    function test_rejects_unknownMsgType() public {
        (bytes memory env,) = _split(DEPOSIT_NOTICE);
        env[1] = 0x63; // 99
        vm.expectRevert(abi.encodeWithSelector(Wire.UnknownMsgType.selector, 99));
        h.decodeEnvelope(env);

        env[1] = 0x00;
        vm.expectRevert(abi.encodeWithSelector(Wire.UnknownMsgType.selector, 0));
        h.decodeEnvelope(env);
    }

    function test_rejects_envelope_wrongLength() public {
        bytes memory short = new bytes(89);
        short[0] = 0x01;
        vm.expectRevert(abi.encodeWithSelector(Wire.Truncated.selector, 90, 89));
        h.decodeEnvelope(short);

        bytes memory long = new bytes(91);
        long[0] = 0x01;
        long[1] = 0x05;
        vm.expectRevert(abi.encodeWithSelector(Wire.TrailingBytes.selector, 1));
        h.decodeEnvelope(long);
    }

    function test_rejects_payload_truncation_and_trailing() public {
        (, bytes memory payload) = _split(DEPOSIT_ACK);
        bytes memory short = new bytes(payload.length - 1);
        for (uint256 i = 0; i < short.length; i++) {
            short[i] = payload[i];
        }
        vm.expectRevert(
            abi.encodeWithSelector(Wire.Truncated.selector, payload.length, payload.length - 1)
        );
        h.decodeDepositAck(short);

        bytes memory long = bytes.concat(payload, hex"00");
        vm.expectRevert(abi.encodeWithSelector(Wire.TrailingBytes.selector, 1));
        h.decodeDepositAck(long);
    }

    function test_rejects_stateSync_trailing() public {
        (, bytes memory payload) = _split(STATE_SYNC);
        bytes memory long = bytes.concat(payload, hex"00");
        vm.expectRevert(abi.encodeWithSelector(Wire.TrailingBytes.selector, 1));
        h.decodeStateSync(long);
    }

    function test_rejects_invalidBool() public {
        (, bytes memory payload) = _split(DEPOSIT_ACK);
        payload[8] = 0x02; // `accepted` byte
        vm.expectRevert(abi.encodeWithSelector(Wire.InvalidBool.selector, 2));
        h.decodeDepositAck(payload);

        (, bytes memory wr) = _split(WITHDRAW_REQUEST);
        wr[65] = 0x03; // `all` byte
        vm.expectRevert(abi.encodeWithSelector(Wire.InvalidBool.selector, 3));
        h.decodeWithdrawRequest(wr);
    }

    function test_rejects_stateSync_rawTooLong() public {
        // spoke_id ‖ count=0 ‖ fee_pot ‖ raw_len=4097 ‖ ...
        bytes memory payload = abi.encodePacked(
            uint64(3), uint8(0), uint128(0), uint16(4097), new bytes(4097), uint64(0)
        );
        vm.expectRevert(abi.encodeWithSelector(Wire.IntegrationRawTooLong.selector, 4097));
        h.decodeStateSync(payload);

        // Encode side enforces the same cap.
        Wire.Envelope memory e;
        Wire.StateSync memory s;
        s.integrationRaw = new bytes(4097);
        s.assets = new Wire.StateSyncAsset[](0);
        vm.expectRevert(abi.encodeWithSelector(Wire.IntegrationRawTooLong.selector, 4097));
        h.encodeStateSync(e, s);
    }

    function test_rejects_stateSync_tooManyAssets() public {
        bytes memory payload = abi.encodePacked(
            uint64(3), uint8(17), new bytes(17 * 33), uint128(0), uint16(0), uint64(0)
        );
        vm.expectRevert(abi.encodeWithSelector(Wire.TooManyAssets.selector, 17));
        h.decodeStateSync(payload);

        Wire.Envelope memory e;
        Wire.StateSync memory s;
        s.assets = new Wire.StateSyncAsset[](17);
        vm.expectRevert(abi.encodeWithSelector(Wire.TooManyAssets.selector, 17));
        h.encodeStateSync(e, s);
    }
}
