// Copyright (c) Aptos Foundation
// Licensed pursuant to the Innovation-Enabling Source Code License, available at https://github.com/aptos-labs/aptos-core/blob/main/LICENSE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: aptos/indexer/v1/filter.proto

package streamv1

import (
	txnv1 "github.com/ewitulsk/SuiOptions/aptos/go-backend/internal/indexerpb/txnv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogicalAndFilters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters []*BooleanTransactionFilter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *LogicalAndFilters) Reset() {
	*x = LogicalAndFilters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicalAndFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalAndFilters) ProtoMessage() {}

func (x *LogicalAndFilters) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalAndFilters.ProtoReflect.Descriptor instead.
func (*LogicalAndFilters) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{0}
}

func (x *LogicalAndFilters) GetFilters() []*BooleanTransactionFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type LogicalOrFilters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters []*BooleanTransactionFilter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *LogicalOrFilters) Reset() {
	*x = LogicalOrFilters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicalOrFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalOrFilters) ProtoMessage() {}

func (x *LogicalOrFilters) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalOrFilters.ProtoReflect.Descriptor instead.
func (*LogicalOrFilters) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{1}
}

func (x *LogicalOrFilters) GetFilters() []*BooleanTransactionFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type TransactionRootFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success         *bool                              `protobuf:"varint,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	TransactionType *txnv1.Transaction_TransactionType `protobuf:"varint,2,opt,name=transaction_type,json=transactionType,proto3,enum=aptos.transaction.v1.Transaction_TransactionType,oneof" json:"transaction_type,omitempty"`
}

func (x *TransactionRootFilter) Reset() {
	*x = TransactionRootFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionRootFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRootFilter) ProtoMessage() {}

func (x *TransactionRootFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRootFilter.ProtoReflect.Descriptor instead.
func (*TransactionRootFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionRootFilter) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *TransactionRootFilter) GetTransactionType() txnv1.Transaction_TransactionType {
	if x != nil && x.TransactionType != nil {
		return *x.TransactionType
	}
	return txnv1.Transaction_TRANSACTION_TYPE_UNSPECIFIED
}

type EntryFunctionFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address    *string `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	ModuleName *string `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3,oneof" json:"module_name,omitempty"`
	Function   *string `protobuf:"bytes,3,opt,name=function,proto3,oneof" json:"function,omitempty"`
}

func (x *EntryFunctionFilter) Reset() {
	*x = EntryFunctionFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryFunctionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryFunctionFilter) ProtoMessage() {}

func (x *EntryFunctionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryFunctionFilter.ProtoReflect.Descriptor instead.
func (*EntryFunctionFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{3}
}

func (x *EntryFunctionFilter) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *EntryFunctionFilter) GetModuleName() string {
	if x != nil && x.ModuleName != nil {
		return *x.ModuleName
	}
	return ""
}

func (x *EntryFunctionFilter) GetFunction() string {
	if x != nil && x.Function != nil {
		return *x.Function
	}
	return ""
}

type UserTransactionPayloadFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntryFunctionFilter *EntryFunctionFilter `protobuf:"bytes,1,opt,name=entry_function_filter,json=entryFunctionFilter,proto3,oneof" json:"entry_function_filter,omitempty"`
}

func (x *UserTransactionPayloadFilter) Reset() {
	*x = UserTransactionPayloadFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTransactionPayloadFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTransactionPayloadFilter) ProtoMessage() {}

func (x *UserTransactionPayloadFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTransactionPayloadFilter.ProtoReflect.Descriptor instead.
func (*UserTransactionPayloadFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{4}
}

func (x *UserTransactionPayloadFilter) GetEntryFunctionFilter() *EntryFunctionFilter {
	if x != nil {
		return x.EntryFunctionFilter
	}
	return nil
}

type UserTransactionFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender        *string                       `protobuf:"bytes,1,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	PayloadFilter *UserTransactionPayloadFilter `protobuf:"bytes,2,opt,name=payload_filter,json=payloadFilter,proto3,oneof" json:"payload_filter,omitempty"`
}

func (x *UserTransactionFilter) Reset() {
	*x = UserTransactionFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTransactionFilter) ProtoMessage() {}

func (x *UserTransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTransactionFilter.ProtoReflect.Descriptor instead.
func (*UserTransactionFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{5}
}

func (x *UserTransactionFilter) GetSender() string {
	if x != nil && x.Sender != nil {
		return *x.Sender
	}
	return ""
}

func (x *UserTransactionFilter) GetPayloadFilter() *UserTransactionPayloadFilter {
	if x != nil {
		return x.PayloadFilter
	}
	return nil
}

type MoveStructTagFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *string `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Module  *string `protobuf:"bytes,2,opt,name=module,proto3,oneof" json:"module,omitempty"`
	Name    *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *MoveStructTagFilter) Reset() {
	*x = MoveStructTagFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveStructTagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveStructTagFilter) ProtoMessage() {}

func (x *MoveStructTagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveStructTagFilter.ProtoReflect.Descriptor instead.
func (*MoveStructTagFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{6}
}

func (x *MoveStructTagFilter) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *MoveStructTagFilter) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

func (x *MoveStructTagFilter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type EventFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StructType          *MoveStructTagFilter `protobuf:"bytes,1,opt,name=struct_type,json=structType,proto3,oneof" json:"struct_type,omitempty"`
	DataSubstringFilter *string              `protobuf:"bytes,2,opt,name=data_substring_filter,json=dataSubstringFilter,proto3,oneof" json:"data_substring_filter,omitempty"`
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{7}
}

func (x *EventFilter) GetStructType() *MoveStructTagFilter {
	if x != nil {
		return x.StructType
	}
	return nil
}

func (x *EventFilter) GetDataSubstringFilter() string {
	if x != nil && x.DataSubstringFilter != nil {
		return *x.DataSubstringFilter
	}
	return ""
}

type APIFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Filter:
	//	*APIFilter_TransactionRootFilter
	//	*APIFilter_UserTransactionFilter
	//	*APIFilter_EventFilter
	Filter isAPIFilter_Filter `protobuf_oneof:"filter"`
}

func (x *APIFilter) Reset() {
	*x = APIFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIFilter) ProtoMessage() {}

func (x *APIFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIFilter.ProtoReflect.Descriptor instead.
func (*APIFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{8}
}

func (m *APIFilter) GetFilter() isAPIFilter_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (x *APIFilter) GetTransactionRootFilter() *TransactionRootFilter {
	if x, ok := x.GetFilter().(*APIFilter_TransactionRootFilter); ok {
		return x.TransactionRootFilter
	}
	return nil
}

func (x *APIFilter) GetUserTransactionFilter() *UserTransactionFilter {
	if x, ok := x.GetFilter().(*APIFilter_UserTransactionFilter); ok {
		return x.UserTransactionFilter
	}
	return nil
}

func (x *APIFilter) GetEventFilter() *EventFilter {
	if x, ok := x.GetFilter().(*APIFilter_EventFilter); ok {
		return x.EventFilter
	}
	return nil
}

type isAPIFilter_Filter interface {
	isAPIFilter_Filter()
}

type APIFilter_TransactionRootFilter struct {
	TransactionRootFilter *TransactionRootFilter `protobuf:"bytes,1,opt,name=transaction_root_filter,json=transactionRootFilter,proto3,oneof"`
}

type APIFilter_UserTransactionFilter struct {
	UserTransactionFilter *UserTransactionFilter `protobuf:"bytes,2,opt,name=user_transaction_filter,json=userTransactionFilter,proto3,oneof"`
}

type APIFilter_EventFilter struct {
	EventFilter *EventFilter `protobuf:"bytes,3,opt,name=event_filter,json=eventFilter,proto3,oneof"`
}

func (*APIFilter_TransactionRootFilter) isAPIFilter_Filter() {}

func (*APIFilter_UserTransactionFilter) isAPIFilter_Filter() {}

func (*APIFilter_EventFilter) isAPIFilter_Filter() {}

type BooleanTransactionFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Filter:
	//	*BooleanTransactionFilter_ApiFilter
	//	*BooleanTransactionFilter_LogicalAnd
	//	*BooleanTransactionFilter_LogicalOr
	//	*BooleanTransactionFilter_LogicalNot
	Filter isBooleanTransactionFilter_Filter `protobuf_oneof:"filter"`
}

func (x *BooleanTransactionFilter) Reset() {
	*x = BooleanTransactionFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aptos_indexer_v1_filter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BooleanTransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanTransactionFilter) ProtoMessage() {}

func (x *BooleanTransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aptos_indexer_v1_filter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanTransactionFilter.ProtoReflect.Descriptor instead.
func (*BooleanTransactionFilter) Descriptor() ([]byte, []int) {
	return file_aptos_indexer_v1_filter_proto_rawDescGZIP(), []int{9}
}

func (m *BooleanTransactionFilter) GetFilter() isBooleanTransactionFilter_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (x *BooleanTransactionFilter) GetApiFilter() *APIFilter {
	if x, ok := x.GetFilter().(*BooleanTransactionFilter_ApiFilter); ok {
		return x.ApiFilter
	}
	return nil
}

func (x *BooleanTransactionFilter) GetLogicalAnd() *LogicalAndFilters {
	if x, ok := x.GetFilter().(*BooleanTransactionFilter_LogicalAnd); ok {
		return x.LogicalAnd
	}
	return nil
}

func (x *BooleanTransactionFilter) GetLogicalOr() *LogicalOrFilters {
	if x, ok := x.GetFilter().(*BooleanTransactionFilter_LogicalOr); ok {
		return x.LogicalOr
	}
	return nil
}

func (x *BooleanTransactionFilter) GetLogicalNot() *BooleanTransactionFilter {
	if x, ok := x.GetFilter().(*BooleanTransactionFilter_LogicalNot); ok {
		return x.LogicalNot
	}
	return nil
}

type isBooleanTransactionFilter_Filter interface {
	isBooleanTransactionFilter_Filter()
}

type BooleanTransactionFilter_ApiFilter struct {
	ApiFilter *APIFilter `protobuf:"bytes,1,opt,name=api_filter,json=apiFilter,proto3,oneof"`
}

type BooleanTransactionFilter_LogicalAnd struct {
	LogicalAnd *LogicalAndFilters `protobuf:"bytes,2,opt,name=logical_and,json=logicalAnd,proto3,oneof"`
}

type BooleanTransactionFilter_LogicalOr struct {
	LogicalOr *LogicalOrFilters `protobuf:"bytes,3,opt,name=logical_or,json=logicalOr,proto3,oneof"`
}

type BooleanTransactionFilter_LogicalNot struct {
	LogicalNot *BooleanTransactionFilter `protobuf:"bytes,4,opt,name=logical_not,json=logicalNot,proto3,oneof"`
}

func (*BooleanTransactionFilter_ApiFilter) isBooleanTransactionFilter_Filter() {}

func (*BooleanTransactionFilter_LogicalAnd) isBooleanTransactionFilter_Filter() {}

func (*BooleanTransactionFilter_LogicalOr) isBooleanTransactionFilter_Filter() {}

func (*BooleanTransactionFilter_LogicalNot) isBooleanTransactionFilter_Filter() {}

var File_aptos_indexer_v1_filter_proto protoreflect.FileDescriptor

var file_aptos_indexer_v1_filter_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x1a, 0x26, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x11, 0x4c, 0x6f, 0x67,
	0x69, 0x63, 0x61, 0x6c, 0x41, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x44,
	0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x22, 0x58, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x4f,
	0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x44, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70, 0x74, 0x6f,
	0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f,
	0x6c, 0x65, 0x61, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0xba,
	0x01, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f,
	0x6f, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x88, 0x01, 0x01, 0x12, 0x61, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x31, 0x2e, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x48, 0x01, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x13,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x88,
	0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x98, 0x01, 0x0a, 0x1c, 0x55, 0x73, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x5e, 0x0a, 0x15, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x13, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x88, 0x01, 0x01, 0x42, 0x18, 0x0a, 0x16, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xae, 0x01,
	0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x88, 0x01, 0x01, 0x12, 0x5a, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61,
	0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x01, 0x52, 0x0d,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x11, 0x0a, 0x0f, 0x5f,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x8a,
	0x01, 0x0a, 0x13, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x54, 0x61, 0x67,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xbd, 0x01, 0x0a, 0x0b,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x0b, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x54, 0x61,
	0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x37, 0x0a, 0x15, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x13, 0x64, 0x61, 0x74, 0x61, 0x53,
	0x75, 0x62, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x42, 0x18, 0x0a, 0x16, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x75, 0x62, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x9f, 0x02, 0x0a, 0x09,
	0x41, 0x50, 0x49, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x61, 0x0a, 0x17, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70, 0x74,
	0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x6f, 0x74, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x15, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x6f, 0x6f, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x61, 0x0a, 0x17,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x15, 0x75, 0x73, 0x65, 0x72, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x42, 0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xbe, 0x02,
	0x0a, 0x18, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0a, 0x61, 0x70,
	0x69, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x50, 0x49, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x09, 0x61,
	0x70, 0x69, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x61, 0x6c, 0x5f, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x41, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x41, 0x6e, 0x64,
	0x12, 0x43, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x4f,
	0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x61, 0x6c, 0x4f, 0x72, 0x12, 0x4d, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c,
	0x5f, 0x6e, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70, 0x74,
	0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f,
	0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61,
	0x6c, 0x4e, 0x6f, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aptos_indexer_v1_filter_proto_rawDescOnce sync.Once
	file_aptos_indexer_v1_filter_proto_rawDescData = file_aptos_indexer_v1_filter_proto_rawDesc
)

func file_aptos_indexer_v1_filter_proto_rawDescGZIP() []byte {
	file_aptos_indexer_v1_filter_proto_rawDescOnce.Do(func() {
		file_aptos_indexer_v1_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_aptos_indexer_v1_filter_proto_rawDescData)
	})
	return file_aptos_indexer_v1_filter_proto_rawDescData
}

var file_aptos_indexer_v1_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aptos_indexer_v1_filter_proto_goTypes = []interface{}{
	(*LogicalAndFilters)(nil),              // 0: aptos.indexer.v1.LogicalAndFilters
	(*LogicalOrFilters)(nil),               // 1: aptos.indexer.v1.LogicalOrFilters
	(*TransactionRootFilter)(nil),          // 2: aptos.indexer.v1.TransactionRootFilter
	(*EntryFunctionFilter)(nil),            // 3: aptos.indexer.v1.EntryFunctionFilter
	(*UserTransactionPayloadFilter)(nil),   // 4: aptos.indexer.v1.UserTransactionPayloadFilter
	(*UserTransactionFilter)(nil),          // 5: aptos.indexer.v1.UserTransactionFilter
	(*MoveStructTagFilter)(nil),            // 6: aptos.indexer.v1.MoveStructTagFilter
	(*EventFilter)(nil),                    // 7: aptos.indexer.v1.EventFilter
	(*APIFilter)(nil),                      // 8: aptos.indexer.v1.APIFilter
	(*BooleanTransactionFilter)(nil),       // 9: aptos.indexer.v1.BooleanTransactionFilter
	(txnv1.Transaction_TransactionType)(0), // 10: aptos.transaction.v1.Transaction.TransactionType
}
var file_aptos_indexer_v1_filter_proto_depIdxs = []int32{
	9,  // 0: aptos.indexer.v1.LogicalAndFilters.filters:type_name -> aptos.indexer.v1.BooleanTransactionFilter
	9,  // 1: aptos.indexer.v1.LogicalOrFilters.filters:type_name -> aptos.indexer.v1.BooleanTransactionFilter
	10, // 2: aptos.indexer.v1.TransactionRootFilter.transaction_type:type_name -> aptos.transaction.v1.Transaction.TransactionType
	3,  // 3: aptos.indexer.v1.UserTransactionPayloadFilter.entry_function_filter:type_name -> aptos.indexer.v1.EntryFunctionFilter
	4,  // 4: aptos.indexer.v1.UserTransactionFilter.payload_filter:type_name -> aptos.indexer.v1.UserTransactionPayloadFilter
	6,  // 5: aptos.indexer.v1.EventFilter.struct_type:type_name -> aptos.indexer.v1.MoveStructTagFilter
	2,  // 6: aptos.indexer.v1.APIFilter.transaction_root_filter:type_name -> aptos.indexer.v1.TransactionRootFilter
	5,  // 7: aptos.indexer.v1.APIFilter.user_transaction_filter:type_name -> aptos.indexer.v1.UserTransactionFilter
	7,  // 8: aptos.indexer.v1.APIFilter.event_filter:type_name -> aptos.indexer.v1.EventFilter
	8,  // 9: aptos.indexer.v1.BooleanTransactionFilter.api_filter:type_name -> aptos.indexer.v1.APIFilter
	0,  // 10: aptos.indexer.v1.BooleanTransactionFilter.logical_and:type_name -> aptos.indexer.v1.LogicalAndFilters
	1,  // 11: aptos.indexer.v1.BooleanTransactionFilter.logical_or:type_name -> aptos.indexer.v1.LogicalOrFilters
	9,  // 12: aptos.indexer.v1.BooleanTransactionFilter.logical_not:type_name -> aptos.indexer.v1.BooleanTransactionFilter
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_aptos_indexer_v1_filter_proto_init() }
func file_aptos_indexer_v1_filter_proto_init() {
	if File_aptos_indexer_v1_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aptos_indexer_v1_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicalAndFilters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aptos_indexer_v1_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicalOrFilters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aptos_indexer_v1_filter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionRootFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aptos_indexer_v1_filter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryFunctionFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aptos_indexer_v1_filter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTransactionPayloadFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aptos_indexer_v1_filter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTransactionFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aptos_indexer_v1_filter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveStructTagFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aptos_indexer_v1_filter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aptos_indexer_v1_filter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aptos_indexer_v1_filter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BooleanTransactionFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_aptos_indexer_v1_filter_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_aptos_indexer_v1_filter_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_aptos_indexer_v1_filter_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_aptos_indexer_v1_filter_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_aptos_indexer_v1_filter_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_aptos_indexer_v1_filter_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_aptos_indexer_v1_filter_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*APIFilter_TransactionRootFilter)(nil),
		(*APIFilter_UserTransactionFilter)(nil),
		(*APIFilter_EventFilter)(nil),
	}
	file_aptos_indexer_v1_filter_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*BooleanTransactionFilter_ApiFilter)(nil),
		(*BooleanTransactionFilter_LogicalAnd)(nil),
		(*BooleanTransactionFilter_LogicalOr)(nil),
		(*BooleanTransactionFilter_LogicalNot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aptos_indexer_v1_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aptos_indexer_v1_filter_proto_goTypes,
		DependencyIndexes: file_aptos_indexer_v1_filter_proto_depIdxs,
		MessageInfos:      file_aptos_indexer_v1_filter_proto_msgTypes,
	}.Build()
	File_aptos_indexer_v1_filter_proto = out.File
	file_aptos_indexer_v1_filter_proto_rawDesc = nil
	file_aptos_indexer_v1_filter_proto_goTypes = nil
	file_aptos_indexer_v1_filter_proto_depIdxs = nil
}
